name: Branches
run-name: Test branches
on:
  push:
    branches:
      - '**'
      - '!staging'
      - '!master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.1'
      - run: npm ci
      - run: npm run test -- --coverage
